<?php

/**
 * Generated by ZF2ModuleCreator
 */
namespace Json;

use Zend\Log\Logger;
use Zend\Router\Http\Segment;
use Zend\ServiceManager\Factory\InvokableFactory;

return array(
	'service_manager' => array(

	),

	'router' => array(
// Uncomment below to add routes
		'routes' => array(
			'album' => array(
				'type' => Segment::class,
				'options' => array(
					'route'    => '/jsonrpc[/:action]',
					'constraints' => array(
						'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
					),

					'defaults' => array(
						'controller' => Controller\JsonController::class,
						'action' => 'index',
					)
				)
			)
		)
	),


	'log' => [
		'MyLogger' => [
			'writers' => [
				[
					'name' => 'stream',
					'priority' => Logger::DEBUG,
					'options' => [
						'stream' => 'php://output',
						'formatter' => [
							'name' => 'MyFormatter',
						],
						'filters' => [
							[
								'name' => 'MyFilter',
							],
						],
					],
				],
			],
		],
	],


	'controllers' => [
		'factories' => [
			Controller\JsonController::class => InvokableFactory::class,
		],
	],
);